package muMLU.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ModelPlusImportedScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.FilteringScope;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Association_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Association_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Association$Uv, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.parentClass$cInh, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:43ae3813-c822-4f87-bb24-008ac68bf0ac(muMLU.constraints)", "7747164616965056255");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          Scope allTilesScope = new ModelPlusImportedScope(SNodeOperations.getModel(_context.getContextNode()), false, CONCEPTS.Class$Xc);
          return new FilteringScope(allTilesScope) {
            public boolean isExcluded(SNode n) {
              boolean isAssocsiation = SNodeOperations.isInstanceOf(n, CONCEPTS.Association$Uv);
              return !(isAssocsiation);
            }
          };
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Association$Uv = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x6b83752c42752e8fL, "muMLU.structure.Association");
    /*package*/ static final SConcept Class$Xc = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, "muMLU.structure.Class");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink parentClass$cInh = MetaAdapterFactory.getReferenceLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, 0x36debd183ff8e32cL, "parentClass");
  }
}
