package muMLUModel_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCreatures = createDescriptorForCreatures();
  /*package*/ final ConceptDescriptor myConceptmetaModel = createDescriptorFormetaModel();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x8fe54b2321f54defL, 0xac58b238fd54820cL, "muMLUMetaModel_lang");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCreatures, myConceptmetaModel);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Creatures:
        return myConceptCreatures;
      case LanguageConceptSwitch.metaModel:
        return myConceptmetaModel;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCreatures() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Creatures", 0x908a38acacf74da5L, 0xa25c2f36d744345aL, 0x36debd183fd1b578L);
    b.class_(false, false, false);
    // extends: muMLUMetaModel_lang.structure.Class
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L);
    b.origin("r:5874116d-9d79-4941-80c4-59615fc96793(muMLUModel_lang.structure)/3953805434725447032");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFormetaModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "metaModel", 0x908a38acacf74da5L, 0xa25c2f36d744345aL, 0x36debd183fd1d7dbL);
    b.class_(false, false, true);
    // extends: muMLUMetaModel_lang.structure.Model
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4beL);
    b.origin("r:5874116d-9d79-4941-80c4-59615fc96793(muMLUModel_lang.structure)/3953805434725455835");
    b.version(3);
    return b.create();
  }
}
