package RPG_lang.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.dataFlow.framework.Program;
import jetbrains.mps.lang.dataFlow.DataFlow;
import jetbrains.mps.lang.dataFlow.framework.AnalysisResult;
import jetbrains.mps.lang.dataFlow.framework.analyzers.ReachabilityAnalyzer;
import jetbrains.mps.lang.dataFlow.framework.instructions.Instruction;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.dataFlow.framework.VarSet;
import jetbrains.mps.lang.dataFlow.framework.analyzers.LivenessAnalyzer;
import jetbrains.mps.lang.dataFlow.framework.instructions.WriteInstruction;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class check_liveness_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_liveness_NonTypesystemRule() {
  }
  public void applyRule(final SNode world, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    Program p = DataFlow.buildProgram(world);

    AnalysisResult<Boolean> reachable = p.analyze(new ReachabilityAnalyzer());
    // Unused code
    for (Instruction i : p.getInstructions()) {
      if (i.getSource() != null && !(reachable.get(i))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning((SNode) i.getSource(), "Unreachable code", "r:1b54dadd-398e-4254-ac29-ec742eb7d95f(RPG_lang.typesystem)", "5997944521777037876", null, errorTarget);
        }
      }
    }

    // Unused assigments
    AnalysisResult<VarSet> result = p.analyze(new LivenessAnalyzer());

    for (Instruction i : p.getInstructions()) {
      if (i instanceof WriteInstruction) {
        WriteInstruction write = (WriteInstruction) i;

        boolean isNeeded = false;
        for (Instruction next : i.succ()) {
          VarSet nextLiveVars = result.get(next);
          if (nextLiveVars.contains(write.getVariable())) {
            isNeeded = true;
            break;
          }
        }

        if (!(isNeeded) && i.getSource() != null) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning((SNode) i.getSource(), "Unused variable", "r:1b54dadd-398e-4254-ac29-ec742eb7d95f(RPG_lang.typesystem)", "5997944521777037336", null, errorTarget);
          }
        }
      }
    }

  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.World$k6;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept World$k6 = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, "RPG_lang.structure.World");
  }
}
