package RPG_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Column;
  private ConceptPresentation props_Grid;
  private ConceptPresentation props_Hero;
  private ConceptPresentation props_Level;
  private ConceptPresentation props_Row;
  private ConceptPresentation props_Tile;
  private ConceptPresentation props_World;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Column:
        if (props_Column == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Column");
          props_Column = cpb.create();
        }
        return props_Column;
      case LanguageConceptSwitch.Grid:
        if (props_Grid == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Grid = cpb.create();
        }
        return props_Grid;
      case LanguageConceptSwitch.Hero:
        if (props_Hero == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Hero");
          props_Hero = cpb.create();
        }
        return props_Hero;
      case LanguageConceptSwitch.Level:
        if (props_Level == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Create a game level in a world");
          cpb.presentationByName();
          props_Level = cpb.create();
        }
        return props_Level;
      case LanguageConceptSwitch.Row:
        if (props_Row == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Row");
          props_Row = cpb.create();
        }
        return props_Row;
      case LanguageConceptSwitch.Tile:
        if (props_Tile == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Tile");
          props_Tile = cpb.create();
        }
        return props_Tile;
      case LanguageConceptSwitch.World:
        if (props_World == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_World = cpb.create();
        }
        return props_World;
    }
    return null;
  }
}
