package RPG_lang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Column = 0;
  public static final int Grid = 1;
  public static final int Hero = 2;
  public static final int Level = 3;
  public static final int Row = 4;
  public static final int Tile = 5;
  public static final int World = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L);
    builder.put(0x698935b6d18cac89L, Column);
    builder.put(0x698935b6d18cac85L, Grid);
    builder.put(0x696b4b7b47a569fcL, Hero);
    builder.put(0x696b4b7b47a4f578L, Level);
    builder.put(0x698935b6d18cac87L, Row);
    builder.put(0x698935b6d18cac8bL, Tile);
    builder.put(0x696b4b7b47a4eb00L, World);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
