package RPG_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptColumn = createDescriptorForColumn();
  /*package*/ final ConceptDescriptor myConceptGrid = createDescriptorForGrid();
  /*package*/ final ConceptDescriptor myConceptHero = createDescriptorForHero();
  /*package*/ final ConceptDescriptor myConceptLevel = createDescriptorForLevel();
  /*package*/ final ConceptDescriptor myConceptRow = createDescriptorForRow();
  /*package*/ final ConceptDescriptor myConceptTile = createDescriptorForTile();
  /*package*/ final ConceptDescriptor myConceptWorld = createDescriptorForWorld();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptColumn, myConceptGrid, myConceptHero, myConceptLevel, myConceptRow, myConceptTile, myConceptWorld);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Column:
        return myConceptColumn;
      case LanguageConceptSwitch.Grid:
        return myConceptGrid;
      case LanguageConceptSwitch.Hero:
        return myConceptHero;
      case LanguageConceptSwitch.Level:
        return myConceptLevel;
      case LanguageConceptSwitch.Row:
        return myConceptRow;
      case LanguageConceptSwitch.Tile:
        return myConceptTile;
      case LanguageConceptSwitch.World:
        return myConceptWorld;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForColumn() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Column", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac89L);
    b.class_(false, false, false);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770505");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGrid() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Grid", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770501");
    b.version(3);
    b.property("Editor", 0x698935b6d18ceb7bL).type(PrimitiveTypeId.STRING).origin("7604668505107786619").done();
    b.aggregate("tile", 0x698935b6d18cac8eL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL).optional(true).ordered(true).multiple(true).origin("7604668505107770510").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHero() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Hero", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345556988");
    b.version(3);
    b.property("lives", 0x696b4b7b47a569ffL).type(PrimitiveTypeId.INTEGER).origin("7596248189345556991").done();
    b.alias("Hero");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLevel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Level", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345527160");
    b.version(3);
    b.aggregate("grid", 0x698935b6d18cacadL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L).optional(false).ordered(true).multiple(false).origin("7604668505107770541").done();
    b.alias("Level");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Row", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac87L);
    b.class_(false, false, false);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770503");
    b.version(3);
    b.aggregate("tile", 0x698935b6d18cac91L).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL).optional(true).ordered(true).multiple(false).origin("7604668505107770513").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Tile", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL);
    b.class_(false, false, false);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770507");
    b.version(3);
    b.property("name", 0x698935b6d18cac93L).type(PrimitiveTypeId.STRING).origin("7604668505107770515").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorld() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "World", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345524480");
    b.version(3);
    b.aggregate("Hero", 0x696b4b7b47a58a0cL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL).optional(false).ordered(true).multiple(false).origin("7596248189345565196").done();
    b.aggregate("Levels", 0x2a240b133398ddL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L).optional(true).ordered(true).multiple(true).origin("11861579007236317").done();
    return b.create();
  }
}
