package RPG_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCreature = createDescriptorForCreature();
  /*package*/ final ConceptDescriptor myConceptDoorTile = createDescriptorForDoorTile();
  /*package*/ final ConceptDescriptor myConceptGrid = createDescriptorForGrid();
  /*package*/ final ConceptDescriptor myConceptHero = createDescriptorForHero();
  /*package*/ final ConceptDescriptor myConceptItem = createDescriptorForItem();
  /*package*/ final ConceptDescriptor myConceptKey = createDescriptorForKey();
  /*package*/ final ConceptDescriptor myConceptLevel = createDescriptorForLevel();
  /*package*/ final ConceptDescriptor myConceptMonster = createDescriptorForMonster();
  /*package*/ final ConceptDescriptor myConceptStandardTile = createDescriptorForStandardTile();
  /*package*/ final ConceptDescriptor myConceptTile = createDescriptorForTile();
  /*package*/ final ConceptDescriptor myConceptTrapTile = createDescriptorForTrapTile();
  /*package*/ final ConceptDescriptor myConceptWorld = createDescriptorForWorld();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCreature, myConceptDoorTile, myConceptGrid, myConceptHero, myConceptItem, myConceptKey, myConceptLevel, myConceptMonster, myConceptStandardTile, myConceptTile, myConceptTrapTile, myConceptWorld);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Creature:
        return myConceptCreature;
      case LanguageConceptSwitch.DoorTile:
        return myConceptDoorTile;
      case LanguageConceptSwitch.Grid:
        return myConceptGrid;
      case LanguageConceptSwitch.Hero:
        return myConceptHero;
      case LanguageConceptSwitch.Item:
        return myConceptItem;
      case LanguageConceptSwitch.Key:
        return myConceptKey;
      case LanguageConceptSwitch.Level:
        return myConceptLevel;
      case LanguageConceptSwitch.Monster:
        return myConceptMonster;
      case LanguageConceptSwitch.StandardTile:
        return myConceptStandardTile;
      case LanguageConceptSwitch.Tile:
        return myConceptTile;
      case LanguageConceptSwitch.TrapTile:
        return myConceptTrapTile;
      case LanguageConceptSwitch.World:
        return myConceptWorld;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCreature() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Creature", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345556988");
    b.version(3);
    b.property("lives", 0x696b4b7b47a569ffL).type(PrimitiveTypeId.INTEGER).origin("7596248189345556991").done();
    b.associate("tileName", 0x533cfac39ab1e022L).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL).optional(false).origin("5997944521771573282").done();
    b.alias("Hero");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDoorTile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "DoorTile", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d98L);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Tile
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521769708952");
    b.version(3);
    b.associate("needed_key", 0x533cfac39a956dabL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d9aL).optional(false).origin("5997944521769708971").done();
    b.associate("to_door", 0x533cfac39ab91b34L).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d98L).optional(false).origin("5997944521772047156").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGrid() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Grid", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770501");
    b.version(3);
    b.property("Editor", 0x698935b6d18ceb7bL).type(PrimitiveTypeId.STRING).origin("7604668505107786619").done();
    b.property("colNr", 0x533cfac39b36f6faL).type(PrimitiveTypeId.INTEGER).origin("5997944521780295418").done();
    b.property("rowNr", 0x533cfac39b36f6fbL).type(PrimitiveTypeId.INTEGER).origin("5997944521780295419").done();
    b.aggregate("tiles", 0x698935b6d18cac8eL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL).optional(true).ordered(true).multiple(true).origin("7604668505107770510").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHero() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Hero", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39abcd3d8L);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Creature
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521772291032");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Item", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d6cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521769708908");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKey() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Key", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d9aL);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Item
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d6cL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521769708954");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLevel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Level", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345527160");
    b.version(3);
    b.aggregate("grid", 0x698935b6d18cacadL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L).optional(false).ordered(true).multiple(false).origin("7604668505107770541").done();
    b.aggregate("monster", 0x533cfac39ac453f2L).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39abcd3d6L).optional(true).ordered(true).multiple(false).origin("5997944521772782578").done();
    b.alias("Level");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMonster() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Monster", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39abcd3d6L);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Creature
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521772291030");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStandardTile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "StandardTile", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d68L);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Tile
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521769708904");
    b.version(3);
    b.aggregate("item", 0x533cfac39a956d6bL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d6cL).optional(true).ordered(true).multiple(false).origin("5997944521769708907").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "Tile", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL);
    b.class_(false, false, false);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7604668505107770507");
    b.version(3);
    b.property("refName", 0x533cfac39aa9ba2bL).type(PrimitiveTypeId.STRING).origin("5997944521771039275").done();
    b.property("colNr", 0x533cfac39aa9d269L).type(PrimitiveTypeId.INTEGER).origin("5997944521771045481").done();
    b.property("rowNr", 0x533cfac39aa9d271L).type(PrimitiveTypeId.INTEGER).origin("5997944521771045489").done();
    b.alias("no tile");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrapTile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "TrapTile", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a91cab5L);
    b.class_(false, false, false);
    // extends: RPG_lang.structure.Tile
    b.super_(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/5997944521769470645");
    b.version(3);
    b.property("lives", 0x533cfac39a91cab7L).type(PrimitiveTypeId.INTEGER).origin("5997944521769470647").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorld() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("RPG_lang", "World", 0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f13a84ac-7857-46e0-9ad0-6118f1254a12(RPG_lang.structure)/7596248189345524480");
    b.version(3);
    b.aggregate("hero", 0x696b4b7b47a58a0cL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39abcd3d8L).optional(false).ordered(true).multiple(false).origin("7596248189345565196").done();
    b.aggregate("levels", 0x2a240b133398ddL).target(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L).optional(true).ordered(true).multiple(true).origin("11861579007236317").done();
    return b.create();
  }
}
