package RPG_lang.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import RPG_lang.behavior.Grid__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Grid_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    ListSequence.fromList(Grid__BehaviorDescriptor.getAllTiles_id4pgbmyJgGQW.invoke(_context.getNode())).visitAll((it) -> _context.getBuilder().build((SNode) it));
  }
}
