package RPG_lang.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import RPG_lang.behavior.World__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class World_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    SNode startTile = ((SNode) SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.hero$P5pr), LINKS.tileName$VQi_));
    ListSequence.fromList(World__BehaviorDescriptor.getAllNeighbors_id5cWYGer8wdR.invoke(_context.getNode(), startTile)).visitAll((it) -> _context.getBuilder().build((SNode) it));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink hero$P5pr = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, 0x696b4b7b47a58a0cL, "hero");
    /*package*/ static final SReferenceLink tileName$VQi_ = MetaAdapterFactory.getReferenceLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, 0x533cfac39ab1e022L, "tileName");
  }
}
