package RPG_lang.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class World_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    _context.getBuilder().emitLabel("gameStart");
    _context.getBuilder().emitJump(_context.getBuilder().before(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.hero$P5pr), LINKS.tileName$VQi_)), "r:399cec5c-55ee-4e86-a1c9-7d6ea326f3b3(RPG_lang.dataFlow)/5066599508442365907");
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.levels$yhqr)).visitAll((it) -> _context.getBuilder().build((SNode) it));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink hero$P5pr = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, 0x696b4b7b47a58a0cL, "hero");
    /*package*/ static final SReferenceLink tileName$VQi_ = MetaAdapterFactory.getReferenceLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, 0x533cfac39ab1e022L, "tileName");
    /*package*/ static final SContainmentLink levels$yhqr = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, 0x2a240b133398ddL, "levels");
  }
}
