package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import RPG_lang.behavior.Creature__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import RPG_lang.behavior.Tile__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Creature_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput()));
    tgs.append(":");
    tgs.append(SNodeOperations.getConcept(ctx.getPrimaryInput()).getName());
    tgs.append("{");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.append("lives = ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.lives$k9MI));
    tgs.append(";");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
    tgs.newLine();
    tgs.append(Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput()));
    tgs.append("_");
    tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.tileName$VQi_)));
    tgs.append(":CreaturesTile (");
    tgs.append(Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput()));
    tgs.append(" -> ");
    tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.tileName$VQi_)));
    tgs.append(")");
    tgs.newLine();

    String creatureStateName = "CS_" + Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput());
    tgs.append(creatureStateName);
    tgs.append(":CreatureState {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.append("moved = False;");
    tgs.newLine();
    tgs.append("fought = False;");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
    tgs.newLine();
    tgs.append(creatureStateName);
    tgs.append("_");
    tgs.append(Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput()));
    tgs.append(":CreatureStateToCreature (");
    tgs.append(creatureStateName);
    tgs.append(" -> ");
    tgs.append(Creature__BehaviorDescriptor.getProcessedName_id3ruJhwZvA6J.invoke(ctx.getPrimaryInput()));
    tgs.append(")");
  }

  private static final class PROPS {
    /*package*/ static final SProperty lives$k9MI = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, 0x696b4b7b47a569ffL, "lives");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink tileName$VQi_ = MetaAdapterFactory.getReferenceLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, 0x533cfac39ab1e022L, "tileName");
  }
}
