package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import RPG_lang.behavior.Grid__BehaviorDescriptor;
import RPG_lang.behavior.Tile__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Grid_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("# All tiles #");
    tgs.newLine();
    for (SNode item : Grid__BehaviorDescriptor.getAllTiles_id4pgbmyJgGQW.invoke(ctx.getPrimaryInput())) {
      tgs.appendNode(item);
    }
    tgs.append("#--- connections between tiles ---#");
    tgs.newLine();
    for (SNode tile : Grid__BehaviorDescriptor.getAllTiles_id4pgbmyJgGQW.invoke(ctx.getPrimaryInput())) {
      tgs.append("# connections for ");
      tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
      tgs.newLine();
      SNode upTile = Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(ctx.getPrimaryInput(), ((int) (SPropertyOperations.getInteger(tile, PROPS.rowNr$u_pf) - 1)), ((int) SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7)));
      if (upTile != null) {
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append("_TO_");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(upTile));
        tgs.append(":TileToTile (");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append(" -> ");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(upTile));
        tgs.append("){");
        tgs.newLine();
        tgs.indent();
        tgs.append("direction = \"up\";");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
      }

      SNode downTile = Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(ctx.getPrimaryInput(), ((int) (SPropertyOperations.getInteger(tile, PROPS.rowNr$u_pf) + 1)), ((int) SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7)));
      if (downTile != null) {
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append("_TO_");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(downTile));
        tgs.append(":TileToTile (");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append(" -> ");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(downTile));
        tgs.append("){");
        tgs.newLine();
        tgs.indent();
        tgs.append("direction = \"down\";");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
      }

      SNode leftTile = Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(ctx.getPrimaryInput(), ((int) SPropertyOperations.getInteger(tile, PROPS.rowNr$u_pf)), ((int) (SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7) - 1)));
      if (leftTile != null) {
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append("_TO_");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(leftTile));
        tgs.append(":TileToTile (");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append(" -> ");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(leftTile));
        tgs.append("){");
        tgs.newLine();
        tgs.indent();
        tgs.append("direction = \"left\";");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
      }

      SNode rightTile = Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(ctx.getPrimaryInput(), ((int) SPropertyOperations.getInteger(tile, PROPS.rowNr$u_pf)), ((int) (SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7) + 1)));
      if (rightTile != null) {
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append("_TO_");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(rightTile));
        tgs.append(":TileToTile (");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
        tgs.append(" -> ");
        tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(rightTile));
        tgs.append("){");
        tgs.newLine();
        tgs.indent();
        tgs.append("direction = \"right\";");
        tgs.newLine();
        tgs.append("}");
        tgs.newLine();
      }

    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty rowNr$u_pf = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, 0x533cfac39aa9d271L, "rowNr");
    /*package*/ static final SProperty colNr$uzx7 = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, 0x533cfac39aa9d269L, "colNr");
  }
}
