package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import RPG_lang.behavior.Item__BehaviorDescriptor;
import RPG_lang.behavior.Tile__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Item_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode tile = SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Tile$RT, false, false);
    tgs.append(Item__BehaviorDescriptor.getProcessedName_id3ruJhwZl4Yr.invoke(ctx.getPrimaryInput()));
    tgs.append(":");
    tgs.append(SNodeOperations.getConcept(ctx.getPrimaryInput()).getName());
    tgs.newLine();
    tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
    tgs.append("_");
    tgs.append(Item__BehaviorDescriptor.getProcessedName_id3ruJhwZl4Yr.invoke(ctx.getPrimaryInput()));
    tgs.append(":StandardToTileItem (");
    tgs.append(Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(tile));
    tgs.append(" -> ");
    tgs.append(Item__BehaviorDescriptor.getProcessedName_id3ruJhwZl4Yr.invoke(ctx.getPrimaryInput()));
    tgs.append(")");
    tgs.newLine();
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Tile$RT = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, "RPG_lang.structure.Tile");
  }
}
