package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import RPG_lang.behavior.Level__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import RPG_lang.behavior.World__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Level_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode world = SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.World$k6, false, false);
    String levelName = Level__BehaviorDescriptor.getProcessedName_id3ruJhwZbEQ3.invoke(ctx.getPrimaryInput());
    tgs.newLine();
    tgs.append(levelName);
    tgs.append(":");
    tgs.append("Level{");
    tgs.newLine();
    tgs.indent();
    tgs.append("name = \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append("\";");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.append(World__BehaviorDescriptor.getProcessedName_id3ruJhwZEX3Q.invoke(world));
    tgs.append("_");
    tgs.append(levelName);
    tgs.append(":WorldToLevel (");
    tgs.append(World__BehaviorDescriptor.getProcessedName_id3ruJhwZEX3Q.invoke(world));
    tgs.append(" -> ");
    tgs.append(levelName);
    tgs.append(")");
    tgs.newLine();
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.grid$OnUt));
    tgs.newLine();

    if (SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.monster$flFy) != null) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.monster$flFy));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept World$k6 = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, "RPG_lang.structure.World");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink grid$OnUt = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L, 0x698935b6d18cacadL, "grid");
    /*package*/ static final SContainmentLink monster$flFy = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L, 0x533cfac39ac453f2L, "monster");
  }
}
