package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import RPG_lang.behavior.Level__BehaviorDescriptor;
import RPG_lang.behavior.Tile__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class StandardTile_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode level = SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Level$rE, false, false);
    String levelName = Level__BehaviorDescriptor.getProcessedName_id3ruJhwZbEQ3.invoke(level);
    String tileName = Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(ctx.getPrimaryInput());
    tgs.append(tileName);
    tgs.append(":StandardTile");
    tgs.newLine();
    tgs.append(levelName);
    tgs.append("_");
    tgs.append(tileName);
    tgs.append(":LevelToTile (");
    tgs.append(levelName);
    tgs.append(" -> ");
    tgs.append(tileName);
    tgs.append(")");
    tgs.newLine();

    if (SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.item$3lTT) != null) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.item$3lTT));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Level$rE = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L, "RPG_lang.structure.Level");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink item$3lTT = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d68L, 0x533cfac39a956d6bL, "item");
  }
}
