package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import RPG_lang.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Creature:
        return new Creature_TextGen();
      case LanguageConceptSwitch.DoorTile:
        return new DoorTile_TextGen();
      case LanguageConceptSwitch.Grid:
        return new Grid_TextGen();
      case LanguageConceptSwitch.Item:
        return new Item_TextGen();
      case LanguageConceptSwitch.Level:
        return new Level_TextGen();
      case LanguageConceptSwitch.StandardTile:
        return new StandardTile_TextGen();
      case LanguageConceptSwitch.Tile:
        return new Tile_TextGen();
      case LanguageConceptSwitch.TrapTile:
        return new TrapTile_TextGen();
      case LanguageConceptSwitch.World:
        return new World_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.World$k6)) {
        String fname = getFileName_World(root);
        String ext = getFileExtension_World(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_World(SNode node) {
    return "models";
  }
  private static String getFileExtension_World(SNode node) {
    return "py";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept World$k6 = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, "RPG_lang.structure.World");
  }
}
