package RPG_lang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import RPG_lang.behavior.Level__BehaviorDescriptor;
import RPG_lang.behavior.Tile__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TrapTile_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode level = SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Level$rE, false, false);
    String levelName = Level__BehaviorDescriptor.getProcessedName_id3ruJhwZbEQ3.invoke(level);
    String tileName = Tile__BehaviorDescriptor.getProcessedName_id3ruJhwZbBX1.invoke(ctx.getPrimaryInput());
    tgs.append(tileName);
    tgs.append(":Trap");
    tgs.newLine();
    tgs.append(levelName);
    tgs.append("_");
    tgs.append(tileName);
    tgs.append(":LevelToTile (");
    tgs.append(levelName);
    tgs.append(" -> ");
    tgs.append(tileName);
    tgs.append(")");
    tgs.newLine();

  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Level$rE = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4f578L, "RPG_lang.structure.Level");
  }
}
