package RPG_lang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ModelPlusImportedScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.FilteringScope;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Creature_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Creature_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Creature$iS, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.tileName$VQi_, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:7b28e06a-1efb-4fcf-aa52-a50cfdf00da0(RPG_lang.constraints)", "5997944521771847366");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          Scope allTilesScope = new ModelPlusImportedScope(SNodeOperations.getModel(_context.getContextNode()), false, CONCEPTS.Tile$RT);
          return new FilteringScope(allTilesScope) {
            public boolean isExcluded(SNode n) {
              boolean isDoor = SNodeOperations.isInstanceOf(n, CONCEPTS.DoorTile$Z4);
              boolean isStandard = SNodeOperations.isInstanceOf(n, CONCEPTS.StandardTile$OX);
              boolean isTrap = SNodeOperations.isInstanceOf(n, CONCEPTS.TrapTile$Rh);
              return !(isDoor || isStandard || isTrap);
            }
          };
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Creature$iS = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, "RPG_lang.structure.Creature");
    /*package*/ static final SConcept Tile$RT = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, "RPG_lang.structure.Tile");
    /*package*/ static final SConcept DoorTile$Z4 = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d98L, "RPG_lang.structure.DoorTile");
    /*package*/ static final SConcept StandardTile$OX = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d68L, "RPG_lang.structure.StandardTile");
    /*package*/ static final SConcept TrapTile$Rh = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a91cab5L, "RPG_lang.structure.TrapTile");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink tileName$VQi_ = MetaAdapterFactory.getReferenceLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a569fcL, 0x533cfac39ab1e022L, "tileName");
  }
}
