package RPG_lang.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.ArrayList;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public final class Grid__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L, "RPG_lang.structure.Grid");

  public static final SMethod<SNode> getTile_id5cWYGer5xL0 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getTile").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5997944521778142272L).languageId(0xbab31d2f4ee9bb39L, 0x3ae3bfbd8089435bL).build2(SMethodBuilder.createJavaParameter(Integer.TYPE, ""), SMethodBuilder.createJavaParameter(Integer.TYPE, ""));
  public static final SMethod<List<SNode>> getDirectNeighbors_id5cWYGer5Gm7 = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getDirectNeighbors").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5997944521778185607L).languageId(0xbab31d2f4ee9bb39L, 0x3ae3bfbd8089435bL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getTile_id5cWYGer5xL0, getDirectNeighbors_id5cWYGer5Gm7);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static SNode getTile_id5cWYGer5xL0(@NotNull SNode __thisNode__, int row, int col) {
    int index = row * SPropertyOperations.getInteger(__thisNode__, PROPS.rowNr$x8Mg) + col;
    if (index < ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.tiles$sgk)).count()) {
      return (SNode) SLinkOperations.getChildren(__thisNode__, LINKS.tiles$sgk).get(index);
    } else {
      return null;
    }
  }
  /*package*/ static List<SNode> getDirectNeighbors_id5cWYGer5Gm7(@NotNull SNode __thisNode__, SNode tile) {
    /*
      Returns a list of the tiles in following format [tile above, tile left, tile right, tile below]

    */

    if (tile == null) {
      return ListSequence.fromList(new ArrayList<SNode>());
    }
    List<SNode> directNeighbors = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(directNeighbors).addElement(Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(__thisNode__, ((int) (SPropertyOperations.getInteger(tile, PROPS.rowNr$u_pf) - 1)), ((int) SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7))));
    ListSequence.fromList(directNeighbors).addElement(Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(__thisNode__, ((int) SPropertyOperations.getInteger(tile, PROPS.rowNr$x8Mg)), ((int) (SPropertyOperations.getInteger(tile, PROPS.colNr$x8zf) - 1))));
    ListSequence.fromList(directNeighbors).addElement(Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(__thisNode__, ((int) SPropertyOperations.getInteger(tile, PROPS.rowNr$x8Mg)), ((int) (SPropertyOperations.getInteger(tile, PROPS.colNr$uzx7) + 1))));
    ListSequence.fromList(directNeighbors).addElement(Grid__BehaviorDescriptor.getTile_id5cWYGer5xL0.invoke(__thisNode__, ((int) (SPropertyOperations.getInteger(tile, PROPS.rowNr$x8Mg) + 1)), ((int) SPropertyOperations.getInteger(tile, PROPS.colNr$x8zf))));
    return directNeighbors;
  }

  /*package*/ Grid__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((SNode) getTile_id5cWYGer5xL0(node, ((int) (Integer) parameters[0]), ((int) (Integer) parameters[1])));
      case 1:
        return (T) ((List<SNode>) getDirectNeighbors_id5cWYGer5Gm7(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty rowNr$x8Mg = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L, 0x533cfac39a738e48L, "rowNr");
    /*package*/ static final SProperty rowNr$u_pf = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, 0x533cfac39aa9d271L, "rowNr");
    /*package*/ static final SProperty colNr$uzx7 = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac8bL, 0x533cfac39aa9d269L, "colNr");
    /*package*/ static final SProperty colNr$x8zf = MetaAdapterFactory.getProperty(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L, 0x533cfac39a738e47L, "colNr");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink tiles$sgk = MetaAdapterFactory.getContainmentLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x698935b6d18cac85L, 0x698935b6d18cac8eL, "tiles");
  }
}
