package RPG_lang.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public final class World__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x696b4b7b47a4eb00L, "RPG_lang.structure.World");

  /*package*/ static final SMethod<List<SNode>> getDirectNeighbors_id5cWYGer8wby = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getDirectNeighbors").modifiers(0, AccessPrivileges.PRIVATE).concept(CONCEPT).baseMethodId(5997944521778922210L).languageId(0xbab31d2f4ee9bb39L, 0x3ae3bfbd8089435bL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  /*package*/ static final SMethod<List<SNode>> getDoorLinkedNeighbors_id5cWYGer8wd1 = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getDoorLinkedNeighbors").modifiers(0, AccessPrivileges.PRIVATE).concept(CONCEPT).baseMethodId(5997944521778922305L).languageId(0xbab31d2f4ee9bb39L, 0x3ae3bfbd8089435bL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<List<SNode>> getAllNeighbors_id5cWYGer8wdR = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getAllNeighbors").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5997944521778922359L).languageId(0xbab31d2f4ee9bb39L, 0x3ae3bfbd8089435bL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getDirectNeighbors_id5cWYGer8wby, getDoorLinkedNeighbors_id5cWYGer8wd1, getAllNeighbors_id5cWYGer8wdR);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static List<SNode> getDirectNeighbors_id5cWYGer8wby(@NotNull SNode __thisNode__, SNode tile) {
    /*
      Returns a list of the tiles in following format [tile above, tile left, tile right, tile below]

    */

    SNode grid = (SNode) SNodeOperations.getParent(tile);
    return Grid__BehaviorDescriptor.getDirectNeighbors_id5cWYGer5Gm7.invoke(grid, tile);
  }
  /*package*/ static List<SNode> getDoorLinkedNeighbors_id5cWYGer8wd1(@NotNull SNode __thisNode__, SNode tile) {
    /*
      Returns a list that contains the tile where the door connects to

    */

    if (!(SNodeOperations.isInstanceOf(tile, CONCEPTS.DoorTile$Z4))) {
      return ListSequence.fromList(new ArrayList<SNode>());
    }
    SNode doorTile = (SNode) tile;
    List<SNode> doorNeighbors = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(doorNeighbors).addElement(SLinkOperations.getTarget(doorTile, LINKS.to_door$Lj_Q));
    return doorNeighbors;
  }
  /*package*/ static List<SNode> getAllNeighbors_id5cWYGer8wdR(@NotNull SNode __thisNode__, SNode startTile) {
    /*
      Returns a list of all neighboring tiles in an reachable order in BST order, from this tile

    */

    List<SNode> allNeighbors = ListSequence.fromList(new ArrayList<SNode>());
    List<SNode> todoNeighbors = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(todoNeighbors).addElement(startTile);

    while (!(todoNeighbors.isEmpty())) {
      SNode processingNeighbor = ListSequence.fromList(todoNeighbors).first();
      allNeighbors.add(processingNeighbor);

      List<SNode> neighbors = World__BehaviorDescriptor.getDirectNeighbors_id5cWYGer8wby.invoke(__thisNode__, processingNeighbor);
      ListSequence.fromList(neighbors).addSequence(ListSequence.fromList(World__BehaviorDescriptor.getDoorLinkedNeighbors_id5cWYGer8wd1.invoke(__thisNode__, processingNeighbor)));
      ListSequence.fromList(neighbors).removeSequence(ListSequence.fromList(allNeighbors));
      ListSequence.fromList(todoNeighbors).removeWhere((it) -> it == null);
      ListSequence.fromList(todoNeighbors).addSequence(ListSequence.fromList(neighbors));

      ListSequence.fromList(todoNeighbors).removeElementAt(0);
    }
    return allNeighbors;
  }

  /*package*/ World__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((List<SNode>) getDirectNeighbors_id5cWYGer8wby(node, (SNode) parameters[0]));
      case 1:
        return (T) ((List<SNode>) getDoorLinkedNeighbors_id5cWYGer8wd1(node, (SNode) parameters[0]));
      case 2:
        return (T) ((List<SNode>) getAllNeighbors_id5cWYGer8wdR(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DoorTile$Z4 = MetaAdapterFactory.getConcept(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d98L, "RPG_lang.structure.DoorTile");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink to_door$Lj_Q = MetaAdapterFactory.getReferenceLink(0x3ae3bfbd8089435bL, 0xbab31d2f4ee9bb39L, 0x533cfac39a956d98L, 0x533cfac39ab91b34L, "to_door");
  }
}
