package muMLU.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Attribute_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append(" = ");
    if (SNodeOperations.getConcept(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.type$HmUn)) == CONCEPTS.AttributeString$ry) {
      tgs.append("\"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.value$apC3));
      tgs.append("\"");
    } else {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.value$apC3));
    }
    tgs.append(";");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$apC3 = MetaAdapterFactory.getProperty(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e4c3L, 0x36debd183ff0441bL, "value");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AttributeString$ry = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e62fL, "muMLU.structure.AttributeString");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink type$HmUn = MetaAdapterFactory.getContainmentLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e4c3L, 0x36debd184020af83L, "type");
  }
}
