package muMLU.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class Class_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append(":");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.parentClass$cInh), PROPS.name$MnvL));

    if (SNodeOperations.getConcept(ctx.getPrimaryInput()) == CONCEPTS.Association$Uv) {
      SNode association = (SNode) ctx.getPrimaryInput();
      tgs.append("(");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(association, LINKS.from_class$Naj6), PROPS.name$MnvL));
      tgs.append(" -> ");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(association, LINKS.to_class$Nay7), PROPS.name$MnvL));
      tgs.append(")");
    }

    if (SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.attributes$8nUU) != null) {
      tgs.append("{");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      for (SNode attribute : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.attributes$8nUU)) {
        tgs.appendNode(attribute);
      }
      ctx.getBuffer().area().decreaseIndent();
      tgs.newLine();
      tgs.append("}");
    }

    if (SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.InheritanceClass$BelF) != null) {
      tgs.append(":Inheritance (");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
      tgs.append(" -> ");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.InheritanceClass$BelF));
    }

    if (SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.attributes_def$bvxG).size() != 0) {
      for (SNode attribute : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.attributes$8nUU)) {
        tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
        tgs.append("_");
        tgs.append(SPropertyOperations.getString(attribute, PROPS.name$MnvL));
        tgs.append(" (");
        tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
        tgs.append(" -> ");
        tgs.appendNode(SLinkOperations.getTarget(attribute, LINKS.type$HmUn));
        tgs.append(" {");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        tgs.append("name");
        tgs.append(" = \"");
        tgs.append(SPropertyOperations.getString(attribute, PROPS.name$MnvL));
        tgs.append("\";");
        tgs.newLine();
        tgs.append("optional");
        tgs.append(" = \"");
        tgs.append(String.valueOf(SPropertyOperations.getBoolean(attribute, PROPS.optional$L2a1)));
        tgs.append("\";");
        tgs.newLine();
        ctx.getBuffer().area().decreaseIndent();
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty optional$L2a1 = MetaAdapterFactory.getProperty(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e4c3L, 0x36debd183fc3e62bL, "optional");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink parentClass$cInh = MetaAdapterFactory.getReferenceLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, 0x36debd183ff8e32cL, "parentClass");
    /*package*/ static final SReferenceLink from_class$Naj6 = MetaAdapterFactory.getReferenceLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x6b83752c42752e8fL, 0x6b83752c42752e91L, "from_class");
    /*package*/ static final SReferenceLink to_class$Nay7 = MetaAdapterFactory.getReferenceLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x6b83752c42752e8fL, 0x6b83752c42752e92L, "to_class");
    /*package*/ static final SContainmentLink attributes$8nUU = MetaAdapterFactory.getContainmentLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, 0x36debd183ff9ed0eL, "attributes");
    /*package*/ static final SReferenceLink InheritanceClass$BelF = MetaAdapterFactory.getReferenceLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, 0x6b83752c42798e6eL, "InheritanceClass");
    /*package*/ static final SContainmentLink type$HmUn = MetaAdapterFactory.getContainmentLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e4c3L, 0x36debd184020af83L, "type");
    /*package*/ static final SContainmentLink attributes_def$bvxG = MetaAdapterFactory.getContainmentLink(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, 0x36debd183fee4ed5L, "attributes_def");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Association$Uv = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x6b83752c42752e8fL, "muMLU.structure.Association");
  }
}
