package muMLU.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import muMLU.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Attribute:
        return new Attribute_TextGen();
      case LanguageConceptSwitch.AttributeBoolean:
        return new AttributeBoolean_TextGen();
      case LanguageConceptSwitch.AttributeInteger:
        return new AttributeInteger_TextGen();
      case LanguageConceptSwitch.AttributeString:
        return new AttributeString_TextGen();
      case LanguageConceptSwitch.Class:
        return new Class_TextGen();
      case LanguageConceptSwitch.Model:
        return new Model_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.Class$Xc)) {
        String fname = getFileName_Class(root);
        String ext = getFileExtension_Class(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
      if (root.getConcept().equals(CONCEPTS.Model$8C)) {
        String fname = getFileName_Model(root);
        String ext = getFileExtension_Model(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_Class(SNode node) {
    return node.getName();
  }
  private static String getFileName_Model(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_Class(SNode node) {
    return null;
  }
  private static String getFileExtension_Model(SNode node) {
    return ".muMLUModel";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Class$Xc = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3cde9L, "muMLU.structure.Class");
    /*package*/ static final SConcept Model$8C = MetaAdapterFactory.getConcept(0x8bb9e0a2a57845d1L, 0xa3194ebbe771fc6eL, 0x36debd183fc3e4beL, "muMLU.structure.Model");
  }
}
