package muMLUModel_lang.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public final class Class__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L, "muMLUModel_lang.structure.Class");

  public static final SMethod<Void> updateAttributes_id3ruJhwZZA6n = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("updateAttributes").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3953805434728374679L).languageId(0xac58b238fd54820cL, 0x8fe54b2321f54defL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(updateAttributes_id3ruJhwZZA6n);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void updateAttributes_id3ruJhwZZA6n(@NotNull SNode __thisNode__) {
    for (SNode attribute : SLinkOperations.getChildren(SLinkOperations.getTarget(__thisNode__, LINKS.classType$$erQ), LINKS.attributes_def$yZAh)) {
      SNode new_attribute = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L, "muMLUModel_lang.structure.Attribute"));
      SPropertyOperations.assign(new_attribute, PROPS.name$MnvL, SPropertyOperations.getString(attribute, PROPS.name$MnvL));
      SPropertyOperations.assign(new_attribute, PROPS.value$xTGC, SPropertyOperations.getString(attribute, PROPS.value$xTGC));
      SLinkOperations.setTarget(new_attribute, LINKS.type$4QYW, SNodeOperations.copyNode(SLinkOperations.getTarget(attribute, LINKS.type$4QYW)));
      ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.attributes$vRZv)).addElement(new_attribute);
    }

  }

  /*package*/ Class__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        updateAttributes_id3ruJhwZZA6n(node);
        return null;
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$xTGC = MetaAdapterFactory.getProperty(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L, 0x36debd183ff0441bL, "value");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink type$4QYW = MetaAdapterFactory.getContainmentLink(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L, 0x36debd184020af83L, "type");
    /*package*/ static final SContainmentLink attributes$vRZv = MetaAdapterFactory.getContainmentLink(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L, 0x36debd183ff9ed0eL, "attributes");
    /*package*/ static final SReferenceLink classType$$erQ = MetaAdapterFactory.getReferenceLink(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L, 0x36debd183ff8e32cL, "classType");
    /*package*/ static final SContainmentLink attributes_def$yZAh = MetaAdapterFactory.getContainmentLink(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L, 0x36debd183fee4ed5L, "attributes_def");
  }
}
