package muMLUModel_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Association;
  private ConceptPresentation props_Attribute;
  private ConceptPresentation props_AttributeInteger;
  private ConceptPresentation props_AttributeString;
  private ConceptPresentation props_AttributeType;
  private ConceptPresentation props_Class;
  private ConceptPresentation props_Inheritance;
  private ConceptPresentation props_Model;
  private ConceptPresentation props_ModelItem;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Association:
        if (props_Association == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Association = cpb.create();
        }
        return props_Association;
      case LanguageConceptSwitch.Attribute:
        if (props_Attribute == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Attribute = cpb.create();
        }
        return props_Attribute;
      case LanguageConceptSwitch.AttributeInteger:
        if (props_AttributeInteger == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Integer");
          props_AttributeInteger = cpb.create();
        }
        return props_AttributeInteger;
      case LanguageConceptSwitch.AttributeString:
        if (props_AttributeString == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("String");
          props_AttributeString = cpb.create();
        }
        return props_AttributeString;
      case LanguageConceptSwitch.AttributeType:
        if (props_AttributeType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AttributeType = cpb.create();
        }
        return props_AttributeType;
      case LanguageConceptSwitch.Class:
        if (props_Class == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Class = cpb.create();
        }
        return props_Class;
      case LanguageConceptSwitch.Inheritance:
        if (props_Inheritance == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Inheritance = cpb.create();
        }
        return props_Inheritance;
      case LanguageConceptSwitch.Model:
        if (props_Model == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Model");
          props_Model = cpb.create();
        }
        return props_Model;
      case LanguageConceptSwitch.ModelItem:
        if (props_ModelItem == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ModelItem = cpb.create();
        }
        return props_ModelItem;
    }
    return null;
  }
}
