package muMLUModel_lang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Association = 0;
  public static final int Attribute = 1;
  public static final int AttributeInteger = 2;
  public static final int AttributeString = 3;
  public static final int AttributeType = 4;
  public static final int Class = 5;
  public static final int Inheritance = 6;
  public static final int Model = 7;
  public static final int ModelItem = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x8fe54b2321f54defL, 0xac58b238fd54820cL);
    builder.put(0x36debd183fc70bf6L, Association);
    builder.put(0x36debd183fc3e4c3L, Attribute);
    builder.put(0x36debd183fc3e636L, AttributeInteger);
    builder.put(0x36debd183fc3e62fL, AttributeString);
    builder.put(0x36debd183fc3e632L, AttributeType);
    builder.put(0x36debd183fc3cde9L, Class);
    builder.put(0x36debd183fc3e4c7L, Inheritance);
    builder.put(0x36debd183fc3e4beL, Model);
    builder.put(0x36debd183fc4195aL, ModelItem);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
