package muMLUModel_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAssociation = createDescriptorForAssociation();
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptAttributeInteger = createDescriptorForAttributeInteger();
  /*package*/ final ConceptDescriptor myConceptAttributeString = createDescriptorForAttributeString();
  /*package*/ final ConceptDescriptor myConceptAttributeType = createDescriptorForAttributeType();
  /*package*/ final ConceptDescriptor myConceptClass = createDescriptorForClass();
  /*package*/ final ConceptDescriptor myConceptInheritance = createDescriptorForInheritance();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptModelItem = createDescriptorForModelItem();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAssociation, myConceptAttribute, myConceptAttributeInteger, myConceptAttributeString, myConceptAttributeType, myConceptClass, myConceptInheritance, myConceptModel, myConceptModelItem);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Association:
        return myConceptAssociation;
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.AttributeInteger:
        return myConceptAttributeInteger;
      case LanguageConceptSwitch.AttributeString:
        return myConceptAttributeString;
      case LanguageConceptSwitch.AttributeType:
        return myConceptAttributeType;
      case LanguageConceptSwitch.Class:
        return myConceptClass;
      case LanguageConceptSwitch.Inheritance:
        return myConceptInheritance;
      case LanguageConceptSwitch.Model:
        return myConceptModel;
      case LanguageConceptSwitch.ModelItem:
        return myConceptModelItem;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAssociation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Association", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc70bf6L);
    b.class_(false, false, false);
    // extends: muMLUModel_lang.structure.ModelItem
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc4195aL);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724748278");
    b.version(3);
    b.property("AssociationType", 0x36debd183fc70c02L).type(PrimitiveTypeId.STRING).origin("3953805434724748290").done();
    b.associate("from", 0x36debd183fc70bfaL).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L).optional(false).origin("3953805434724748282").done();
    b.associate("to", 0x36debd183fc70bfbL).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L).optional(false).origin("3953805434724748283").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Attribute", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724541635");
    b.version(3);
    b.property("optional", 0x36debd183fc3e62bL).type(PrimitiveTypeId.BOOLEAN).origin("3953805434724541995").done();
    b.property("value", 0x36debd183ff0441bL).type(PrimitiveTypeId.STRING).origin("3953805434727449627").done();
    b.aggregate("type", 0x36debd184020af83L).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e632L).optional(false).ordered(true).multiple(false).origin("3953805434730622851").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "AttributeInteger", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e636L);
    b.class_(false, false, false);
    // extends: muMLUModel_lang.structure.AttributeType
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e632L);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724542006");
    b.version(3);
    b.alias("Integer");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "AttributeString", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e62fL);
    b.class_(false, false, false);
    // extends: muMLUModel_lang.structure.AttributeType
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e632L);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724541999");
    b.version(3);
    b.alias("String");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "AttributeType", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e632L);
    b.class_(false, true, false);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724542002");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Class", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L);
    b.class_(false, false, true);
    // extends: muMLUModel_lang.structure.ModelItem
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc4195aL);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724535785");
    b.version(3);
    b.property("status", 0x36debd184002008bL).type(PrimitiveTypeId.INTEGER).origin("3953805434728611979").done();
    b.associate("classType", 0x36debd183ff8e32cL).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L).optional(true).origin("3953805434728014636").done();
    b.aggregate("attributes_def", 0x36debd183fee4ed5L).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L).optional(true).ordered(true).multiple(true).origin("3953805434727321301").done();
    b.aggregate("attributes", 0x36debd183ff9ed0eL).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c3L).optional(true).ordered(true).multiple(true).origin("3953805434728082702").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInheritance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Inheritance", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4c7L);
    b.class_(false, false, false);
    // extends: muMLUModel_lang.structure.ModelItem
    b.super_(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc4195aL);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724541639");
    b.version(3);
    b.associate("subClass", 0x36debd183fc3e626L).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L).optional(false).origin("3953805434724541990").done();
    b.associate("parentClass", 0x36debd183fc3e627L).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3cde9L).optional(false).origin("3953805434724541991").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "Model", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc3e4beL);
    b.class_(false, false, true);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724541630");
    b.version(3);
    b.aggregate("lines", 0x36debd183fc3e4c0L).target(0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc4195aL).optional(true).ordered(true).multiple(true).origin("3953805434724541632").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModelItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("muMLUModel_lang", "ModelItem", 0x8fe54b2321f54defL, 0xac58b238fd54820cL, 0x36debd183fc4195aL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5f46a042-a058-42c1-be75-7edabc224d94(muMLUModel_lang.structure)/3953805434724555098");
    b.version(3);
    return b.create();
  }
}
